server:
  port: 80
spring:
  application:
    name: wh-crowd-zuul
  redis:
    host: 192.168.25.122
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*"  # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应 头）
  routes:
    crowd-portal:
      service-id: wh-crowd-auth
      path: /**   # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    crowd-project:
      service-id: wh-crowd-project
      path: /project/**
    crowd-order:
      service-id: wh-crowd-order
      path: /order/**
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
