server:
  port: 5000
spring:
  application:
    name: wh-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.25.122
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
aliyun:
  oss:
    access-key-id: 
    access-key-secret: 
    bucket-domain: https://wanghu5517.oss-cn-beijing.aliyuncs.com
    bucket-name: wanghu5517
    end-point: https://oss-cn-beijing.aliyuncs.com
