server:
  port: 5000
spring:
  application:
    name: wh-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.25.122
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
aliyun:
  oss:
    access-key-id: LTAI5tLxuTbduh1NLNbPgcz3
    access-key-secret: kZdPoFiP7ighWqUYOr7qqGbvvMqhqp
    bucket-domain: http://wanghu5517@1966316916778166.onaliyun.com
    bucket-name: wanghu5517
    end-point: http://oss-cn-beijing.aliyuncs.com