server:
  port: 4000
spring:
  application:
    name: wh-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    host: https://cxwg.market.alicloudapi.com
    path: /sendSms
    method: POST
    appcode: 693ec7493c5d47e6a07ad6196ab54c3e
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000